default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: felp_development

test:
  <<: *default
  database: felp_test

production:
  <<: *default
  database: felp_production
  username: joe84
  password: 626084jo
