# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4796e5ce729e7b069686866724d8283ce2efd7c29e99b51c044b322afee93c1d305b32a60ea9dce7a757eb1f1714038a091604e7df6093a75742b3fcd631bc3c

test:
  secret_key_base: d0524a3f277e205336d80f62668be996038bc0fffee890d6fa27fc3c1f5949c3673b76aedc88a8b97f1fa1ed599a20dd23fa10ee5fd8166df24d3c34a4546f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
